# Generated by Django 5.0.6 on 2024-07-27 18:28

import attendee.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=50)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=attendee.models.get_file_path
                    ),
                ),
                ("descriptions", models.TextField(max_length=500)),
                (
                    "status",
                    models.BooleanField(default=False, help_text="0=default, 1=Hidden"),
                ),
                (
                    "trending",
                    models.BooleanField(
                        default=False, help_text="0=default, 1=trending"
                    ),
                ),
                ("meta_title", models.CharField(max_length=50)),
                ("meta_keywords", models.CharField(max_length=50)),
                ("meta_descriptions", models.TextField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=50)),
                (
                    "event_image",
                    models.ImageField(
                        blank=True, null=True, upload_to=attendee.models.get_file_path
                    ),
                ),
                ("small_descriptions", models.CharField(max_length=250)),
                ("quantity", models.IntegerField()),
                ("descriptions", models.TextField(max_length=500)),
                ("original_price", models.FloatField()),
                ("sellingl_price", models.FloatField()),
                (
                    "status",
                    models.BooleanField(default=False, help_text="0=default, 1=Hidden"),
                ),
                (
                    "trending",
                    models.BooleanField(
                        default=False, help_text="0=default, 1=trending"
                    ),
                ),
                ("tag", models.CharField(max_length=50)),
                ("meta_title", models.CharField(max_length=50)),
                ("meta_keywords", models.CharField(max_length=50)),
                ("meta_descriptions", models.TextField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="attendee.category",
                    ),
                ),
            ],
        ),
    ]
