# Generated by Django 5.0.6 on 2024-07-28 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendee", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="sellingl_price",
            new_name="selling_price",
        ),
    ]
