# Generated by Django 5.0.6 on 2024-07-30 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendee", "0003_contact"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contact",
        ),
    ]
