# Generated by Django 5.0.6 on 2024-08-02 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendee", "0006_queue"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=150)),
                ("lname", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=150)),
                ("phone", models.ImageField(max_length=150, upload_to="")),
                ("tottal_price", models.FloatField()),
                ("payment_id", models.CharField(max_length=250, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Confirmed and Processing", "Confirmed and Processing"),
                            ("Booking Confirmed", "Booking Confirmed"),
                            ("Pending", "Pending"),
                        ],
                        default="In Progress",
                        max_length=150,
                    ),
                ),
                ("message", models.TextField(null=True)),
                ("tracking_no", models.CharField(max_length=150, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookingItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.FloatField()),
                ("quantity", models.IntegerField()),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="attendee.booking",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="attendee.event"
                    ),
                ),
            ],
        ),
    ]
