# Generated by Django 5.0.6 on 2024-08-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendee", "0007_booking_bookingitem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="tottal_price",
            new_name="total_price",
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("Booking Confirmed", "Booking Confirmed"),
                    ("Pending", "Pending"),
                    ("Confirmed and Processing", "Confirmed and Processing"),
                ],
                default="In Progress",
                max_length=150,
            ),
        ),
    ]
